version: "3.9"

services:
  db:
    image: postgis/postgis:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: db_dev
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    container_name: api
    volumes:
      - ../../api:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=db_dev
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
